services:
  glances:
    container_name: glances
    deploy:
      resources:
        reservations:
          memory: "268435456"
        limits:
          memory: 15841M
    environment:
      - GLANCES_OPT=-w
    image: nicolargo/glances:4.1.2.1-full
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Glances/icon.png
    pid: host
    ports:
      - target: 61208
        published: "61208"
        protocol: tcp
      - target: 61209
        published: "61209"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /mnt
        target: /mnt
    x-casaos:
      envs:
        - container: GLANCES_OPT
          description:
            en_us: Glances mode
            zh_cn: Glances模式
      ports:
        - container: "61208"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口
          protocol: tcp
        - container: "61209"
          description:
            en_us: Glances API port
            zh_cn: Glances API 端口
          protocol: tcp
      volumes:
        - container: /var/run/docker.sock
          description:
            en_us: Docker socket
            zh_cn: Docker socket
        - container: /mnt
          description:
            en_us: Drivers mount folder
            zh_cn: 驱动器挂载点
    devices: []
    cap_add: []
    command: []
    network_mode: bridge
    privileged: false
    hostname: glances
    cpu_shares: 90
