services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.shemp == true
      restart_policy:
        condition: on-failure
